# Generated by Django 3.1.6 on 2021-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthyfriends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='point_ct',
            field=models.IntegerField(default=0),
        ),
    ]
