# Generated by Django 3.1.7 on 2021-04-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthyfriends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
