# Generated by Django 3.2 on 2021-04-14 01:34

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import healthyfriends.models


class Migration(migrations.Migration):

    dependencies = [
        ('healthyfriends', '0002_auto_20210330_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='name',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='points',
        ),
        migrations.AddField(
            model_name='goals',
            name='current_progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='goals',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='goals',
            name='desired_progress',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='goals',
            name='goal_type',
            field=models.CharField(choices=[('Y-Metrics', 'QUANTIFIED'), ('N-Metrics', 'TEXTUAL')], default='N-Metrics', max_length=9),
        ),
        migrations.AddField(
            model_name='goals',
            name='last_seven_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7), default=healthyfriends.models.init_last_seven_days, size=7),
        ),
        migrations.AddField(
            model_name='goals',
            name='last_update',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='goals',
            name='metric',
            field=models.CharField(default='', max_length=50),
        ),
    ]
